apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
    app: demo
spec:
  selector:
    name: flask-app 
  type: NodePort
  ports:
   - port: 8000
     targetPort: 8000
     protocol: TCP
