version: '3.1'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    environment:
      - REDIS_ENDPOINT=redis
      - REDIS_PORT=6379
      - VERSION=1.1.1
    volumes:
      - redis_data:/data
  flask:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    healthcheck:
      test: curl --fail http://0.0.0.0:8000/get || exit 1
      interval: 5s
      timeout: 2s
      retries: 5
volumes:
  redis_data: